### PR TITLE
Hyper 1.0.x compatibility

### LINKED ISSUE #6: Hyper 1.0 support
It seems that there was some markup/elektron changes in newest Hyper version, which causes window actions to be visible again.
screen shot 2016-12-13 at 8 15 39 pm

### PR DESCRIPTION
**Pull request by rastasheep**
Resolves #6 

Note: I've tested this on MacOS 10.12.2, shouldn't be platform related

### CODE REVIEW

**Comment by jancborchardt** [comment]
@rastasheep @robbschiller yup, this is also pretty much how we do it with [hyperminimal](https://github.com/jancborchardt/hyperminimal/), see: https://github.com/jancborchardt/hyperminimal/blob/master/index.js#L50-L55

@albinekb just found your plugin now! Wish I had earlier so I could have just added Ubuntu support instead of writing a whole new one. ;D

**Comment by albinekb** [comment]
Sweet thanks!

**Comment by albinekb** [comment]
released as 1.0.0 @rastasheep @jancborchardt

**Comment by rastasheep** [comment]
Awsm, it seems to work. :)

**Pull request merged**
